### ISSUE TITLE
Authentication request with username field in Reg-Req-2 F-10

### ISSUE THREAD

**Issue by rlin1** [fido-alliance/conformance-tool-issues#13]
1.	Reg-Req-2 F-10 Registration request sent with “op”: “Auth” value. Request content below
[
  {
     "challenge":"LTVDV2k3WXJYeG1HZ2NzYXpwcEl2RmNlR3ZwNl9PSkFzTEZ1WXZVVg",
     "header":{  "appID":"",  "op":"Auth",         
"serverData":"eyJ0ZXN0Y2FzZSI6ICJDbGllbnQtUmVnLVJlcS0yLUYtMTAtMSIsICJ0aW1lc3RhbXAiOiAxNDc5MjA1Nzk3LjgwMjg5NCwgImNoYWxsZW5nZSI6ICItNUNXaTdZclh4bUdnY3NhenBwSXZGY2VHdnA2X09KQXNMRnVZdlVWIn0=",
        	"upv":{ "major":1,  "minor":0    }
     },
     "policy":{
        "accepted":[ [ {  "aaid":[ "1234#5678"  ] } ]  ]
     },
     "username":"hello@test.com"
  }
]

**Comment by rlin1** [comment]
Not sure what the expected server behavior is and why.
It is part of registration request tests, but the request looks like a valid authentication request (see Op field).
At this time components are NOT required to test whether unknown are present (username in this case) and to complain.

**Comment by herrjemand** [comment]
@rlin1 
Reg-Req-2 F-10 F-10 In the header field Header.op = "Auth"

Authenticator being sent RegistrationRequest with Header.op set to "Auth". Authenticator must fail with protocol error.

**Comment by rlin1** [comment]
How does the authenticator know it is a Registration request (and not an Authentication Request)?

**Comment by rlin1** [comment]
the messages look very similar (except Header.op field and username).
So in the end it might be an auth request without ever registering the authenticator before (leading to  UAF_ASM_STATUS_ACCESS_DENIED being returned to the FIDO Client).

**Comment by jenkay** [comment]
@rlin1 @herrjemand 

Is this just a negative test case that looks at 'reg' op.header, expects 'reg' op.header, but purposefully sends an 'auth' op.header?

**Comment by mlourie** [comment]
I think the op.header value defines the request type.

**Comment by herrjemand** [comment]
Resolved in the latest build.

**Comment by mlourie** [comment]
We are still seeing the op.header is set to Auth.

[{"challenge":"LTVDV2k3WXJYeG1HZ2NzYXpwcEl2RmNlR3ZwNl9PSkFzTEZ1WXZVVg","header":{"appID":"","op":"Auth","serverData":"eyJ0ZXN0Y2FzZSI6ICJDbGllbnQtUmVnLVJlcS0yLUYtMTAtMSIsICJ0aW1lc3RhbXAiOiAxNDc5MjA1Nzk3LjgwMjg5NCwgImNoYWxsZW5nZSI6ICItNUNXaTdZclh4bUdnY3NhenBwSXZGY2VHdnA2X09KQXNMRnVZdlVWIn0=","upv":{"major":1,"minor":0}},"policy":{"accepted":[[{"aaid":["4e4e#4010"]}]]},"username":"hello@test.com"}]
