### ISSUE TITLE
UAF 1.1 - Server-Auth-Req-2 P-3 Tool compares transaction text to empty string

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#43]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
The last assert in the test case is incorrect.

assert.strictEqual(contentString, ''). The empty string should be replaced with 'Transfer 200$ to Bob\'s account?'.

```
P-3 Get AuthenticationRequest with transaction confirmation request, for authenticator that supports transaction of type "text/plain". Check "transaction" field is of type SEQUENCE, and for each member, check that: (a) "Transaction.contentType" must be set to "text/plain" (b) "Transaction.content" must be of type DOMString and must not be empty (c) "Transaction.content" must be base64url encoded (d) "Transaction.content" must decode to UTF-8 that is max of 200 characters ‣
AssertionError: expected 'Transfer 200$ to Bob\'s account?' to equal ''
    at rest.register.get.then.then.then.then (eval at compileCode

```

**Comment by herrjemand** [comment]
Resolved

**Comment by vens1** [comment]
@herrjemand There is still a problem with the fix. The code in Server-Auth-Req-2.js always makes the assertion fail as the base64url encoded string is being asserted to be equal to the decoded string. 

```
                let contentString = B64URLToUTF8(transaction.content);

                assert.strictEqual(transaction.content, contentString, `For text/plain authenticator, Transaction.content MUST be the base64url encoding of the text transaction! \n Expected ${transaction.content} to equal ${contentString}!`); 
```

```
P-3 Get AuthenticationRequest with transaction confirmation request, for authenticator that supports transaction of type "text/plain". Check "transaction" field is of type SEQUENCE, and for each member, check that: (a) "Transaction.contentType" must be set to "text/plain" (b) "Transaction.content" must be of type DOMString and must not be empty (c) "Transaction.content" must be base64url encoded (d) "Transaction.content" must decode to UTF-8 that is max of 200 characters ‣
AssertionError: For text/plain authenticator, Transaction.content MUST be the base64url encoding of the text transaction! 
 Expected VHJhbnNmZXIgMjAwJCB0byBCb2IncyBhY2NvdW50Pw to equal Transfer 200$ to Bob's account?!: expected 'VHJhbnNmZXIgMjAwJCB0byBCb2IncyBhY2NvdW50Pw' to equal 'Transfer 200$ to Bob\'s account?'
    at rest.register.get.then.then.then.then (eval at compileCode (js/sandbox.j
```
